#Replace the application id below with yours
application: twilio-alpha
version: 1-0
runtime: go
api_version: go1
handlers:
- url: /.*
  script: _go_app

env_variables:
  TWILIO_ACCOUNT_SID: 
  TWILIO_AUTH_TOKEN: 
  TWILIO_NUMBER: 
